### ISSUE TITLE
To accept comments in posts

### ISSUE THREAD

**Issue by gildasio** [ariestiyansyah/naringu#1]
Add comments it would be beautiful! :D 

Could use [Disqus](http://disqus.com/) for it.

**Comment by gildasio** [comment]
The merge request [#2](https://github.com/ariestiyansyah/naringu/pull/2) was then accept, so this issue was made.

**Comment by RizRiyz** [comment]
Issue has been fixed https://github.com/ariestiyansyah/naringu/pull/2
