### ISSUE TITLE
Gh-pages contain error

### ISSUE THREAD

**Issue by ariestiyansyah** [ariestiyansyah/naringu#6]
Hey @gjuniioor please check http://naringu.oonlab.com there are some error after merge the commit in issue #5 , please fix this issue by regenerate gh-pages with your style, I'll add you as collaborator so you have the full access.

Please let me know

Thanks

**Comment by gildasio** [comment]
@ariestiyansyah , this erro happend because the merge, look in [my place](gjuniioor.github.io/naringu), don't have erro.

After you add me as collaborator I think that I can fix it because the error are in your repository and I need to commit direct in this case.

See u later.
